### ISSUE TITLE
upgrade tutorial

### ISSUE THREAD

**Issue by Ktysai** [Interbotix/interbotix_ros_arms#13]
Hi there,

Is there a recommended way to update the files from interbotix_ws?

All the best!

**Comment by swinterbotix** [comment]
Just type `git pull` in your command terminal...

`:~/interbotix_ws/src/interbotix_ros_arms$ git pull`

**Comment by Ktysai** [comment]
@swinterbotix Thanks!

I've had to do rosdep update & install and a catkin_make to make all available
