### ISSUE TITLE
Rx 150

### ISSUE THREAD

**Issue by sayyidabeegam** [Interbotix/interbotix_ros_arms#33]
Hello
I am using RX 150 arm.
I want to create arm movement for some goals continuously.
I have gone through the Python example codes and think to modify them.
But the problem is that will work only with hardware, since it using arm node.
But I want to verify the working in gazebo before implementing it into hardware.
What will do?
Is there any already build code for this to moving goal positions(with multiple goal points), which is able to test with simulation?
Thanks in advance

**Comment by swiz23** [comment]
Hi @sayyidabeegam,

Currently, the Python examples do not work out of the box in Gazebo. Also, this repo is in legacy mode, so you should really use the [interbotix_ros_manipulators](https://github.com/Interbotix/interbotix_ros_manipulators) repo. There's a bit more support for Gazebo in that repository (mainly the addition of joint position controllers for all arms). Even in that repo though, it is still not yet possible to do what you're proposing. I plan to create a ROS node that mimics the arm node but is made for Gazebo or Rviz, but don't have a timeline for this yet...

**Comment by sayyidabeegam** [comment]
Thank you
