### ISSUE TITLE
Issue with Forearm-Roll Joint Limit on Wx250s

### ISSUE THREAD

**Issue by febert** [Interbotix/interbotix_ros_arms#36]
Hello,

I have a wx250s and the joint limits on the forearm_roll joint (in other words the 4th joint, or joint_angles[3]) are very restrictive.
When the forearm_roll joint is in is neutral position (for example when grasping something from a table with a vertical gripper orientation) the forearm_roll is very close to one of its joint limits which are at +- 3.141.

Also I noticed that the initial joint position flips based on the position of the servo in the moment when I run arm_run.lauch. The neutral orientation of the joint can either correspond to -3.141 or +3.141 depending on how the joint is oriented when I run arm_run.launch.

Is there any way to relocate the joint limits and make the initial joint position the same for all initial robot confgurations?

Thanks!

I'm also posting this in the newer repo, since it also has the same problem: https://github.com/Interbotix/interbotix_ros_manipulators/issues/2

**Comment by swiz23** [comment]
Issue was addressed in the newer repo.
