### ISSUE TITLE
Can't find Dynamixel ID '1'

### ISSUE THREAD

**Issue by rpl-as-ucl** [Interbotix/interbotix_ros_arms#44]
[ERROR] [1620733866.815769341]: [TxRxResult] There is no status packet!
[ERROR] [1620733866.818041616]: Can't find Dynamixel ID '1'
[ INFO] [1620733866.854153629]: ID : 2, Model Number : 1020
[ INFO] [1620733866.890146776]: ID : 3, Model Number : 1020
[ INFO] [1620733866.926099673]: ID : 4, Model Number : 1020
[ INFO] [1620733866.962087394]: ID : 5, Model Number : 1020
[ INFO] [1620733866.998098667]: ID : 6, Model Number : 1020
[ INFO] [1620733867.034083870]: ID : 7, Model Number : 1060
[ INFO] [1620733867.070090000]: ID : 8, Model Number : 1060
[ INFO] [1620733867.130085319]: Robot torqued off!
[ERROR] [1620733867.130132052]: [DynamixelDriver] Failed to get the Tool
[ERROR] [1620733867.130152614]: Failed to write value[0] on items[Min_Position_Limit] to [ID : 1]

Any hope for help.  This is a new arm, never used before, so not sure what is wrong.

**Comment by swiz23** [comment]
See my answer [here](https://github.com/Interbotix/interbotix_ros_manipulators/issues/7#issuecomment-840246322).

**Comment by swiz23** [comment]
Closing as answer is discussed in the link above.
