### ISSUE TITLE
Compiler error on Ubuntu Linux with Nvidia Drivers: No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so'

### ISSUE THREAD

**Issue by EvdoTheo** [Interbotix/interbotix_ros_arms#7]
I did a fresh install of Ubuntu Linux 18.04 64-bit desktop. Since my computer has an Nvidia GPU, I installed Nvidia's Linux drivers (version 440.33.01). I then followed  Linux installation instructions but ran into the following error while compiling:

`Base path: /home/evdo/catkin_ws
Source space: /home/evdo/catkin_ws/src
Build space: /home/evdo/catkin_ws/build
Devel space: /home/evdo/catkin_ws/devel
Install space: /home/evdo/catkin_ws/install
####
####
####
####
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target interbotix_descriptions_xacro_generated_to_devel_space_
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target graph_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target visualization_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target tf_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target visualization_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target visualization_msgs_generate_messages_eus
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target tf_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target tf_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target tf_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target tf_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target trajectory_msgs_generate_messages_nodejs
[  0%] Built target visualization_msgs_generate_messages_cpp
[  0%] Built target moveit_msgs_generate_messages_nodejs
[  0%] Built target visualization_msgs_generate_messages_py
[  0%] Built target trajectory_msgs_generate_messages_lisp
[  0%] Built target trajectory_msgs_generate_messages_eus
[  0%] Built target graph_msgs_generate_messages_py
[  0%] Built target trajectory_msgs_generate_messages_cpp
[  0%] Built target moveit_msgs_generate_messages_cpp
[  0%] Built target object_recognition_msgs_generate_messages_cpp
[  0%] Built target moveit_msgs_generate_messages_py
[  0%] Built target shape_msgs_generate_messages_cpp
[  0%] Built target graph_msgs_generate_messages_eus
[  0%] Built target moveit_msgs_generate_messages_lisp
[  0%] Built target shape_msgs_generate_messages_eus
[  0%] Built target shape_msgs_generate_messages_py
[  0%] Built target _interbotix_moveit_interface_generate_messages_check_deps_MoveItPlan
[  0%] Built target trajectory_msgs_generate_messages_py
[  0%] Built target shape_msgs_generate_messages_nodejs
[  0%] Built target moveit_msgs_generate_messages_eus
[  0%] Built target moveit_ros_planning_gencfg
[  0%] Built target object_recognition_msgs_generate_messages_lisp
[  0%] Built target graph_msgs_generate_messages_cpp
[  0%] Built target object_recognition_msgs_generate_messages_py
[  0%] Built target object_recognition_msgs_generate_messages_eus
[  0%] Built target octomap_msgs_generate_messages_eus
[  0%] Built target object_recognition_msgs_generate_messages_nodejs
[  0%] Built target octomap_msgs_generate_messages_lisp
[  0%] Built target octomap_msgs_generate_messages_nodejs
[  0%] Built target octomap_msgs_generate_messages_py
[  0%] Built target shape_msgs_generate_messages_lisp
[  0%] Built target moveit_ros_manipulation_gencfg
[  1%] Built target interbotix_moveit_interface_generate_messages_cpp
[  1%] Built target graph_msgs_generate_messages_lisp
[  1%] Built target nav_msgs_generate_messages_py
[  1%] Built target octomap_msgs_generate_messages_cpp
[  1%] Built target std_srvs_generate_messages_py
[  1%] Built target nav_msgs_generate_messages_nodejs
[  1%] Built target nav_msgs_generate_messages_cpp
[  1%] Built target nav_msgs_generate_messages_eus
[  1%] Built target nav_msgs_generate_messages_lisp
[  1%] Built target map_msgs_generate_messages_lisp
[  1%] Built target map_msgs_generate_messages_eus
[  1%] Built target map_msgs_generate_messages_nodejs
[  1%] Built target map_msgs_generate_messages_cpp
[  1%] Built target _catkin_empty_exported_target
[  1%] Built target map_msgs_generate_messages_py
[  1%] Built target std_srvs_generate_messages_cpp
[  1%] Built target std_srvs_generate_messages_eus
[  1%] Built target control_msgs_generate_messages_lisp
[  1%] Built target std_srvs_generate_messages_lisp
[  1%] Built target control_msgs_generate_messages_cpp
[  1%] Built target std_srvs_generate_messages_nodejs
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_RobotInfo
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_RegisterValues
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_JointCommands
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_OperatingModes
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_SingleCommand
[  1%] Built target _interbotix_sdk_generate_messages_check_deps_FirmwareGains
[  1%] Built target control_msgs_generate_messages_py
[  1%] Built target control_msgs_generate_messages_nodejs
[  1%] Built target interbotix_sdk_xacro_generated_to_devel_space_
[  1%] Built target control_msgs_generate_messages_eus
[  1%] Built target interbotix_diagnostic_tool_xacro_generated_to_devel_space_
[  1%] Built target topic_tools_generate_messages_cpp
[  1%] Built target topic_tools_generate_messages_py
[  1%] Built target topic_tools_generate_messages_lisp
[  1%] Built target topic_tools_generate_messages_nodejs
[  1%] Built target topic_tools_generate_messages_eus
[  1%] Built target diagnostic_msgs_generate_messages_py
[  1%] Built target diagnostic_msgs_generate_messages_nodejs
[  1%] Built target diagnostic_msgs_generate_messages_cpp
[  1%] Built target diagnostic_msgs_generate_messages_eus
[  1%] Built target diagnostic_msgs_generate_messages_lisp
[  1%] Built target interbotix_pid_control_xacro_generated_to_devel_space_
[  1%] Built target interbotix_joy_control_xacro_generated_to_devel_space_
[  1%] Built target interbotix_puppet_control_xacro_generated_to_devel_space_
[  1%] Built target interbotix_turret_control_xacro_generated_to_devel_space_
[  1%] Built target interbotix_gazebo_xacro_generated_to_devel_space_
[  3%] Built target interbotix_moveit_interface_generate_messages_py
[  3%] Built target _interbotix_joy_control_generate_messages_check_deps_ArmJoyControl
[  5%] Built target interbotix_moveit_interface_generate_messages_nodejs
[  6%] Built target interbotix_moveit_interface_generate_messages_lisp
[  6%] Built target _interbotix_diagnostic_tool_generate_messages_check_deps_MotorTemps
[  8%] Built target interbotix_moveit_interface_generate_messages_eus
[ 16%] Built target interbotix_sdk_generate_messages_lisp
[ 35%] Built target interbotix_sdk_generate_messages_py
[ 35%] Built target interbotix_sdk_generate_messages_eus
[ 42%] Built target interbotix_sdk_generate_messages_nodejs
[ 43%] Built target _interbotix_turret_control_generate_messages_check_deps_TurretJoyControl
[ 50%] Built target interbotix_sdk_generate_messages_cpp
[ 52%] Built target interbotix_joy_control_generate_messages_py
[ 53%] Built target interbotix_joy_control_generate_messages_lisp
[ 55%] Built target interbotix_joy_control_generate_messages_nodejs
[ 57%] Built target interbotix_joy_control_generate_messages_eus
[ 58%] Built target interbotix_joy_control_generate_messages_cpp
[ 58%] Built target interbotix_moveit_interface_generate_messages
[ 60%] Built target interbotix_diagnostic_tool_generate_messages_nodejs
[ 61%] Built target interbotix_diagnostic_tool_generate_messages_lisp
[ 63%] Built target interbotix_diagnostic_tool_generate_messages_eus
[ 65%] Built target interbotix_diagnostic_tool_generate_messages_cpp
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by '/home/evdo/catkin_ws/devel/lib/interbotix_pid_control/pid_control_node'.  Stop.
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by '/home/evdo/catkin_ws/devel/lib/interbotix_puppet_control/puppet_control_node'.  Stop.
CMakeFiles/Makefile2:6838: recipe for target 'interbotix_ros_arms/interbotix_examples/interbotix_pid_control/CMakeFiles/pid_control_node.dir/all' failed
make[1]: *** [interbotix_ros_arms/interbotix_examples/interbotix_pid_control/CMakeFiles/pid_control_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:7014: recipe for target 'interbotix_ros_arms/interbotix_examples/interbotix_puppet_control/CMakeFiles/puppet_control_node.dir/all' failed
make[1]: *** [interbotix_ros_arms/interbotix_examples/interbotix_puppet_control/CMakeFiles/puppet_control_node.dir/all] Error 2
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by '/home/evdo/catkin_ws/devel/lib/interbotix_puppet_control/puppet_control_single_node'.  Stop.
CMakeFiles/Makefile2:7131: recipe for target 'interbotix_ros_arms/interbotix_examples/interbotix_puppet_control/CMakeFiles/puppet_control_single_node.dir/all' failed
make[1]: *** [interbotix_ros_arms/interbotix_examples/interbotix_puppet_control/CMakeFiles/puppet_control_single_node.dir/all] Error 2
[ 67%] Built target interbotix_diagnostic_tool_generate_messages_py
[ 71%] Built target interbotix_turret_control_generate_messages_cpp
[ 71%] Built target interbotix_turret_control_generate_messages_eus
[ 72%] Built target interbotix_turret_control_generate_messages_nodejs
[ 76%] Built target moveit_interface_node
[ 78%] Built target interbotix_turret_control_generate_messages_py
[ 80%] Built target interbotix_turret_control_generate_messages_lisp
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed
`
I tried to update the symbolic link as follows, but nothing happend:

$ sudo rm /usr/lib/x86_64-linux-gnu/libGL.so
$ sudo ln -s /usr/lib/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so

**Comment by evdokimos** [comment]
>
